### ISSUE TITLE
Add Firebase Auth using other methods present for user/donor

### ISSUE THREAD

**Issue by 1HazArd1** [Diversion2k22/Samarpan#6]
-  **Add Firebase Authentication for user/donor using Google Facebook and Twitter**
- Also update the related buttons 
- Remove the uncessary images from drawable folder
- Remove the action bar

**Comment by Rohit-554** [comment]
Can i work I am Rohit from your project contributor

**Comment by 1HazArd1** [comment]
Sign in through Google Facebook and Twitter has been removed because it was creating problem collecting the required information from the user.
